#!/usr/bin/env node
/* Turn a run into a comparison report.

     node research/score.js                  # newest run
     node research/score.js <run-id>

   Reads the run's summary.json (and re-reads the per-item JSONL for the detail
   tables) and writes report.md next to it. Nothing here knows which model is
   which: same metrics, same table, same ordering rule for everyone. */
'use strict';
var fs = require('fs');
var path = require('path');
var store = require('./lib/store.js');
var tasksReg = require('./tasks/index.js');

function newestRun() {
  if (!fs.existsSync(store.ROOT)) return null;
  var dirs = fs.readdirSync(store.ROOT).filter(function (d) {
    return d !== 'cache' && fs.existsSync(path.join(store.ROOT, d, 'summary.json'));
  }).sort();
  return dirs.length ? dirs[dirs.length - 1] : null;
}

function fmt(v, digits) {
  if (v == null) return '-';
  if (typeof v !== 'number') return String(v);
  if (!isFinite(v)) return '-';
  return v.toFixed(digits == null ? 3 : digits);
}

function better(a, b, lowerIsBetter) {
  if (a == null) return false;
  if (b == null) return true;
  return lowerIsBetter ? a < b : a > b;
}

function report(runIdArg) {
  var id = runIdArg || newestRun();
  if (!id) throw new Error('no runs found - run research/run.js first');
  var dir = path.join(store.ROOT, id);
  var summary = JSON.parse(fs.readFileSync(path.join(dir, 'summary.json'), 'utf8'));
  var meta = JSON.parse(fs.readFileSync(path.join(dir, 'meta.json'), 'utf8'));

  var models = meta.models.map(function (m) { return m.id; });
  var taskIds = meta.tasks.map(function (t) { return t.id; });
  var cell = {};
  summary.results.forEach(function (r) { cell[r.model + '|' + r.task] = r; });

  var L = [];
  L.push('# Model comparison: ' + id);
  L.push('');
  L.push('Same process, same prompts, same parsing, same scoring - one row per model.');
  L.push('Generated by `research/score.js`. Raw per-item responses are in this directory.');
  L.push('');
  L.push('- **Search backend:** `' + meta.search + '`' + (meta.search === 'fixtures' ? ' (offline, closed corpus of the report’s 79 sources - reproducible)' : ' (live web - results move between runs)'));
  L.push('- **Settings:** temperature ' + meta.settings.temperature + ', seed ' + meta.settings.seed +
    ', repeats ' + meta.settings.repeats + (meta.settings.limit ? ', limit ' + meta.settings.limit + ' items/task' : '') + ', node ' + meta.node);
  L.push('- **Started:** ' + meta.started);
  L.push('');

  /* Headline table */
  L.push('## Headline');
  L.push('');
  var header = ['Model'].concat(taskIds.map(function (t) {
    var task = tasksReg.TASKS[t];
    return t + '<br><sub>' + task.headline + (task.headlineLowerIsBetter ? ' (lower better)' : '') + '</sub>';
  }));
  L.push('| ' + header.join(' | ') + ' |');
  L.push('|' + header.map(function () { return '---'; }).join('|') + '|');

  var best = {};
  taskIds.forEach(function (t) {
    var lower = !!tasksReg.TASKS[t].headlineLowerIsBetter;
    models.forEach(function (m) {
      var c = cell[m + '|' + t];
      if (c && better(c.headline.value, best[t], lower)) best[t] = c.headline.value;
    });
  });

  models.forEach(function (m) {
    var row = ['`' + m + '`'];
    taskIds.forEach(function (t) {
      var c = cell[m + '|' + t];
      if (!c) { row.push('-'); return; }
      var v = c.headline.value;
      var s = fmt(v);
      if (v != null && best[t] != null && Math.abs(v - best[t]) < 1e-9) s = '**' + s + '**';
      row.push(s);
    });
    L.push('| ' + row.join(' | ') + ' |');
  });
  L.push('');

  /* Reliability: how often the output was even usable. */
  L.push('## Output reliability');
  L.push('');
  L.push('`schema_ok` is the share of answers that parsed into the required shape; ' +
    '`repaired` is the share that needed the harness to repair the JSON (fences, trailing commas, bare keys). ' +
    'A high repair rate is not disqualifying, but it is a real operational cost.');
  L.push('');
  L.push('| Model | Task | schema_ok | repaired | call errors | refusals | mean ms | tokens in | tokens out |');
  L.push('|---|---|---|---|---|---|---|---|---|');
  summary.results.forEach(function (r) {
    L.push('| `' + r.model + '` | ' + r.task + ' | ' + (r.schema_ok * 100).toFixed(0) + '% | ' +
      (r.repair_rate * 100).toFixed(0) + '% | ' + r.call_errors + ' | ' + r.refusals + ' | ' +
      (r.mean_ms == null ? '-' : r.mean_ms) + ' | ' + r.tokens_in + ' | ' + r.tokens_out + ' |');
  });
  L.push('');

  /* Per-task detail with every metric the task reports. */
  L.push('## Per-task detail');
  taskIds.forEach(function (t) {
    var task = tasksReg.TASKS[t];
    L.push('');
    L.push('### ' + t + ' - ' + task.title);
    L.push('');
    L.push('_' + task.measures + '_');
    L.push('');
    var keys = [];
    models.forEach(function (m) {
      var c = cell[m + '|' + t];
      if (!c) return;
      Object.keys(c.metrics).forEach(function (k) {
        if (typeof c.metrics[k] !== 'object' && keys.indexOf(k) < 0) keys.push(k);
      });
    });
    L.push('| Model | ' + keys.join(' | ') + ' |');
    L.push('|' + ['---'].concat(keys.map(function () { return '---'; })).join('|') + '|');
    models.forEach(function (m) {
      var c = cell[m + '|' + t];
      if (!c) return;
      L.push('| `' + m + '` | ' + keys.map(function (k) { return fmt(c.metrics[k]); }).join(' | ') + ' |');
    });

    /* Confusion matrices, where the task reports one. */
    models.forEach(function (m) {
      var c = cell[m + '|' + t];
      if (!c || !c.metrics.confusion) return;
      var labels = Object.keys(c.metrics.confusion).sort();
      if (!labels.length) return;
      var got = {};
      labels.forEach(function (w) { Object.keys(c.metrics.confusion[w]).forEach(function (g) { got[g] = true; }); });
      var cols = Object.keys(got).sort();
      L.push('');
      L.push('<details><summary>Confusion, <code>' + m + '</code> (rows = correct, columns = answered)</summary>');
      L.push('');
      L.push('| | ' + cols.join(' | ') + ' |');
      L.push('|' + ['---'].concat(cols.map(function () { return '---'; })).join('|') + '|');
      labels.forEach(function (w) {
        L.push('| **' + w + '** | ' + cols.map(function (g) { return c.metrics.confusion[w][g] || 0; }).join(' | ') + ' |');
      });
      L.push('');
      L.push('</details>');
    });
  });

  /* Determinism note, because it is not uniform across providers. */
  L.push('');
  L.push('## Determinism');
  L.push('');
  L.push('What each backend actually honoured. This is not uniform: on the current Claude models ' +
    '`temperature` is rejected outright, so those runs are not temperature-pinned and repeated runs ' +
    'may differ. Treat cross-family gaps smaller than run-to-run variance as noise, and use ' +
    '`--repeats` to measure that variance before reading much into a small difference.');
  L.push('');
  L.push('| Model | temperature | seed |');
  L.push('|---|---|---|');
  models.forEach(function (m) {
    var rows = [];
    taskIds.forEach(function (t) {
      var f = path.join(dir, m + '__' + t + '.jsonl');
      if (fs.existsSync(f)) rows = rows.concat(store.readJsonl(f).slice(0, 1));
    });
    var d = (rows[0] && rows[0].determinism) || {};
    L.push('| `' + m + '` | ' + (d.temperature || 'unknown') + ' | ' + (d.seed || 'unknown') + ' |');
  });

  L.push('');
  L.push('## Reading this honestly');
  L.push('');
  L.push('- **`forecast` measures agreement, not accuracy.** None of the 22 forecasts has resolved, so the reference is the report’s own probabilities. A model that disagrees may turn out to be right. Watch `hedge_rate`: answering 0.5 everywhere buys a middling score while saying nothing.');
  L.push('- **The mock entries are not models.** `mock-oracle` answers from the gold label and `mock-weak` answers naively; they exist to prove a perfect and a floor score are both reachable, so the scorer is known to discriminate.');
  L.push('- **`find-sources` scores the query, not the model’s knowledge**, because the retriever is held fixed. Swap `--search` to compare retrievers instead.');
  L.push('- **Prompts are deliberately plain** - no provider-specific formatting, no role-play, no family-specific tricks. A prompt tuned for one model would invalidate the comparison. They are in `research/prompts/` if you want to change them; change them for everyone at once.');
  L.push('');

  var out = path.join(dir, 'report.md');
  fs.writeFileSync(out, L.join('\n'));
  return out;
}

if (require.main === module) {
  try {
    console.log(path.relative(process.cwd(), report(process.argv[2])));
  } catch (e) {
    console.error(String(e.message || e));
    process.exit(1);
  }
}
module.exports = { report, newestRun };
